### ISSUE TITLE
Calculation of showspeed/hidespeed broken for P2 side

### ISSUE THREAD

**Issue by Ksylatarsh** [ikemen-engine/Ikemen-GO#1224] opened 2023-05-08 21:27 UTC
### Describe the bug

For some reason, combo counter and lifebar action's show/hide speed is broken if you change the localcoord of the fight.def (in my tests it stopped sliding after 360x240) this must be a coordinate issue.

### To Reproduce

[test_case.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11425267/test_case.zip)

Latest nightly build (05/08/23) with the fight.def edited to showcase this error, just get into a versus match and do a small 2 hit combo to P1.

### Expected behavior

It should slide in-correctly and smoothly depending on the show/hide speed just like P1's.

### Screenshots / Video

https://user-images.githubusercontent.com/126763763/236938882-4441d66f-3fee-4707-b9da-126fa11204e4.mp4

Expected behavior vs. wrong behavior

### Engine Version (or source code date)

Nightly - 05/08

### Operating system

Windows

### Extra context or search terms

combo counter, lifebar action, hidespeed, showspeed, lifebars, fight.def

**Comment by potsmugen** [comment] 2023-05-24 16:42
I think this is just because you changed the localcoord without adjust the position of the text accordingly.

**Comment by K4thos** [comment] 2024-09-03 23:58
Closing as a duplicate of #1095 for maintenance purposes.

**Closed by K4thos** 2024-09-03 23:58 UTC
Labels: bug, duplicate, issue: lifebar
