### ISSUE TITLE
rank arcade issue

### ISSUE THREAD

**Issue by ngmanning1005** [ikemen-engine/Ikemen-GO#1358] opened 2023-08-06 13:33 UTC
when i go into arcade or team arcade it takes me to the rankings and then it sends me back to the menu what's going on here

**Comment by K4thos** [comment] 2023-08-06 13:53
works as intended. Use any other key than start or modify key assigned to opening ranking.

**Closed by K4thos** 2023-08-06 13:53 UTC

**Comment by ngmanning1005** [comment] 2023-08-06 13:59
tried that and it didn't work it just takes me back are you sure that's the answer?

**Comment by K4thos** [comment] 2023-08-06 14:13
The second reason might be that there isn't a single fight possible due to the order settings in select.def.

The Issues page is reserved for bug reports. If you're convinced that you've found one, then prepare a proper test case, not just a one-sentence question. There is a template for reporting bugs, and this page describes how to make a proper issue submission: https://github.com/ikemen-engine/Ikemen-GO/blob/master/CONTRIBUTING.md#submit
