### ISSUE TITLE
IkemenGO memory leak

### ISSUE THREAD

**Issue by softmgr** [ikemen-engine/Ikemen-GO#1706] opened 2024-03-24 06:03 UTC
### Describe the bug

After running IkemenGO for a long time, memory leaks are serious. For example, when you first start the program, the memory usage is about 300MB, and after running it continuously for several hours, the memory usage will rise to more than 10GB.

### To Reproduce

1. Open IkemenGO.
2. Do not operate it manually, it will automatically enter demo mode.
3. Keep running for more than several hours.

### Expected behavior

I hope it can automatically release a portion of unused memory instead of growing the memory footprint indefinitely.

### Engine Version (or source code date)

0.99.0

### Operating system

Windows

**Comment by SuperFromND** [comment] 2024-03-30 00:37
I suspect this is related to or even a duplicate of https://github.com/ikemen-engine/Ikemen-GO/issues/265. Is this being done with a default (read: fresh from [the releases page](https://github.com/ikemen-engine/Ikemen-GO/releases/latest)) install of Ikemen GO?

**Comment by softmgr** [comment] 2024-05-06 09:28
> I suspect this is related to or even a duplicate of https://github.com/ikemen-engine/Ikemen-GO/issues/265. Is this being done with a default (read: fresh from [the releases page](https://github.com/ikemen-engine/Ikemen-GO/releases/latest)) install of Ikemen GO?


Yes, I downloaded and installed it from the release page. Additionally, I also compiled the development version, and the same issue occurred.

**Comment by K4thos** [comment] 2024-09-03 15:18
Closing as a duplicate for maintenance.

**Closed as completed by K4thos** 2024-09-03 15:18 UTC
Labels: duplicate, group: performance

**Comment by Sillydeviant** [comment] 2024-11-30 21:41
im having this exact issue excpet it crashes after 11.4(my max ram) is reached

**Comment by Sillydeviant** [comment] 2025-08-21 23:49
issue still persists btw

it seems to be only on amd ryzen too

**Comment by Sillydeviant** [comment] 2025-08-21 23:50
hopefully gets fixed?
