### ISSUE TITLE
Issues with Vega from Fausto.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#598] opened 2022-07-01 18:48 UTC
First one: the EX effect isn't working on Ikemen.

https://user-images.githubusercontent.com/77592586/176953112-49bdc7fc-8603-4cf0-9c8a-0ef9a06efecd.mp4

https://user-images.githubusercontent.com/77592586/176953134-acb190c1-e3de-4fc4-b7a1-36443cdd78ab.mp4

Second one: Ikemen only displays the correct palletes if I skip intro.

https://user-images.githubusercontent.com/77592586/176953254-a6d97de6-c4db-4b90-813c-e836d7419683.mp4

https://user-images.githubusercontent.com/77592586/176953356-b4e4a33a-1f11-49d3-83bb-4af14c76f8a6.mp4

[Vega POTS.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9031042/Vega.POTS.zip)

**Comment by K4thos** [comment] 2022-07-01 20:00
1. fixed in above commit
2. can't reproduce on github build, so I assume it's already fixed

https://user-images.githubusercontent.com/8928195/176961380-254d1192-ca30-4191-a924-faf46f4f8451.mp4

**Closed by K4thos** 2022-07-01 20:00 UTC
