### ISSUE TITLE
Auto turning may not switch targets correctly

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1109] opened 2023-03-30 07:59 UTC
### Describe the bug

While tagging for instance, the enemy may prefer to turn towards the resting player than the active player. I think that if NoTurnTarget is asserted, the char should face the next closest enemy. This may have been the behavior in 0.98.2 because this bug did not happen there.

### To Reproduce

1. Download this light tag modification: [tag bug.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11109219/tag.bug.zip)
2. Tag out while jumping over the enemy

### Expected behavior

Same as 0.98.2 I suppose.

### Screenshots / Video

https://user-images.githubusercontent.com/107247004/228769440-6922f2e3-5999-4173-bdd8-4e599daeaa1c.mp4

In addition, I think Standby characters should be more "invisible" to the enemy, so to speak. Like when they are KO. In this example for instance, P2 redirection is referring to the enemy outside the screen until the moment the character turns.

### Engine Version (or source code date)

28/03/2023

### Operating system

Windows

**Comment by K4thos** [comment] 2023-03-30 21:24
@NeatUnsou, PR #1112 partially reverts your #804 that introduced this regression. I don't quite understand the purpose of this code since #606 no longer happens without those changes and P2 already skips defeated enemies using boolean flag during function call. Waiting for confirmation from you if those changes can be safely reverted or if they were introduced to fix some other bug.

**Comment by NeatUnsou** [comment] 2023-03-30 22:50
the purpose of this code is to reproduce a very minor feature of MUGEN.
in MUGEN's simul mode, a character recognized as p2 is held on a different axis than enemynear. In other words, p2 and enemynear may refer to different characters, even if they are both alive.
enemynear simply refers to the closest character. 
p2 initially refers to the closest character as well, but it must be at least 30 pixels closer than the currently referenced character for it to switch to another character.
I would like to do another fix for this.

**Closed** 2023-03-31 00:24 UTC
Labels: bug, regression
