### ISSUE TITLE
Bug: Engine Crash

### ISSUE THREAD

**Issue by djonskin** [ikemen-engine/Ikemen-GO#805] opened 2023-01-09 21:21 UTC
**Describe the bug**
I am crashing on startup.

external/script/main.lua:2147: attempt to compare string with number
stack traceback:
external/script/main.lua:2147: in main chunk
[G]: ?

All I could really gather is that something's up with the way the syntax for rmax and rmin is written. After some troubleshooting, a (now closed) PR I did got me back into the program.

**To Reproduce**
I was just trying to START THIS. I'm using the STOCK Elecbyte screenpack, but nothing else should be erroneous. This is with the latest compiled build.
 Here's the steps anyone with a Windows 10 x64 machine can do to reproduce my crash, though I've had no luck so far with another reproduction from another individual.
1: Fresh bin folder (from a new compilation of the latest IKEMEN) with no modifications. This folder has only Data, External and the latest Ikemen GO exe compiled from github.
2: Then add from the Elecbyte pack repository the necessary System.def components.
3: Add fonts in from the pack and it errors on startup.

**Expected behavior**
A normal startup.

**Screenshots / Video**
![image (2)](https://user-images.githubusercontent.com/106702560/211409973-b611ba28-e9da-4a48-8b68-267d58b976f1.png)

**Platform (please complete the following information):**
 - Engine Version -- LATEST IKEMEN BUILD.
 - OS: Windows 10

**Comment by K4thos** [comment] 2023-01-09 22:25
can't reproduce

**Comment by djonskin** [comment] 2023-01-09 22:38
I mentioned it's the latest build. Can you link yours then?

**Comment by djonskin** [comment] 2023-01-14 18:42
Submitted PR for proposed syntax change in main.lua ratiomatches section.

**Comment by K4thos** [comment] 2023-01-18 00:25
please upload whole build that crashes (drag and drop zip here), without your changes to lua files. Still can't reproduce it based on your #816 steps.

**Comment by JJMP4** [comment] 2023-01-18 07:04
Hey any updates? I had a similar issue but mine was had the numbers 2155 instead, I believe it's something to do with ratiomatches.

**Comment by K4thos** [comment] 2023-01-18 12:16
No. I've said in my previous post what has to be provided for us to be able to reproduce it locally.

**Comment by djonskin** [comment] 2023-01-20 18:26
Now included in description K4thos.

**Comment by slzero-X** [comment] 2023-01-20 18:35
He followed exactly as you told him, and still not the same results. I detect a "hardware issue"

**Comment by djonskin** [comment] 2023-01-20 19:26
> He followed exactly as you told him, and still not the same results. I detect a "hardware issue"

That itself is pretty vague, sl. My issue isn't there if I use that PR code, and how current of a GO version do I need to compile with?? I get an exe out of it, nothing errors until I have to run it and it complains about code deep down inside Main.lua related to RatioMatches that should have nothing to do with main ops.

**Comment by K4thos** [comment] 2023-01-20 23:05
thanks for uploading the build. It also crashes to me, so it's reproducible locally, which is a good thing. I will compare the files with Beyond Compare app to see if anything differs here outside executable. Probably this weekend, if I find enough time to test it.

**Comment by slzero-X** [comment] 2023-01-20 23:25
I see, that explains it. An oversight that was somehow missed.

**Comment by K4thos** [comment] 2023-01-21 21:09
I've confirmed the files. The only difference is the executable, which means the result of your compilation is wrong. After coping Ikemen_GO.exe compiled by myself it works. There is nothing to fix on lua side in this case. You will have to find a way to compile correctly, if you want to compile from source code, or wait for official stable release.

**Comment by djonskin** [comment] 2023-01-21 23:08
> I've compared the files. The only difference is the executable, which means the result of your compilation is somehow wrong. After coping Ikemen_GO.exe compiled by myself it works. Which means there is nothing to fix on lua side in this case. You will have to find a way to compile correctly, if you want to compile from source code, or wait for official stable release.

I can get you a build with the normal icons. All I threw in with it was a nonstandard icon syso. You mean to tell me this deviates because it can't handle some game icons? Do I have to redo the syso? I've done it without it and still got the error, so I can't buy that.

**Comment by K4thos** [comment] 2023-01-21 23:23
I can't be sure what's going on on your end, my guess would be that you're building using different version of dependencies (js version of gopherLua in this case) than the one specified in go.mod and go.sum or using different compiler, or something like that. There won't be any changes made to lua scripts blindly, until the problem shows up on our end (for example after updating dependencies).

**Comment by djonskin** [comment] 2023-01-21 23:29
So let me get this straight... the .mod file or whatever in here that's pointing to the dependencies, you're saying, aren't apparently being used? What are they downloading then? Shouldn't the compiler have errored before I've even got to this point? Isn't that what's used in the Get file?

**Comment by K4thos** [comment] 2023-01-22 00:49
I've just verified that one of the dependencies (most likely gopherLua) have breaking change that causes it. Since we're going to update go.mod for the new release anyway it's something that has to be solved, so the report is valid. Not sure yet if the problem is on our side or the dependency introduced a bug (in which case we would have to specifically target older release). I'm investigating it. Will be fixed one way or another.

**Comment by K4thos** [comment] 2023-01-22 01:18
The bug is on dependency side and should be reported there, nothing to fix on our side. Verified with this code:
```lua
local a, b, c= "1", "3", "1"
a, b, c= tonumber(a), tonumber(b) or a, tonumber(c)
print(a, type(a), b, type(b), c, type(c))
```
gopher-lua v1.0.0 prints
```lua
print(1, number, 3, string, 1, number)
```
Expected types for all 3 is number. You should use version v0.0.0-20220504180219-658193537a64 - the version referenced in go.mod file.

You can use this batch to download intended versions of dependencies
[build.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10473500/build.zip)

**Closed by K4thos** 2023-01-22 01:18 UTC
Labels: bug
