### ISSUE TITLE
Dr.Kahl's Robot malfunctions in IKEMEN GO.

### ISSUE THREAD

**Issue by CybeRuler2023** [ikemen-engine/Ikemen-GO#1442] opened 2023-10-13 12:29 UTC
### Describe the bug

Dark Ruler's Dr.Kahl's Robot character work properly up to mugen 1.1, but Malfunction in Ikemen go. This character uses a player-type helper that introduces part destruction to embody the original work.
The helper moves by recognizing command input from the main body.
However, this helper's state Time is fixed at 0 or remains silent even when a command is entered.
We've tried many things, but we haven't been able to fix this bug, so the remake of this character is being delayed.
Phase 1 of this character consists of helpers and recognizes command input and moves the state.
There seems to be a bug in the part helper body(24,32) rather than the super armor.
There is also a bug where the sound of parts being destroyed keeps repeating (it is not shown in the video for reasons that may cause dissonance).

### To Reproduce

1. Get Dr.Kahl's Robot. [[Get Dr.Kahl's Robot. ](https://www.mediafire.com/file/9sxva5tj1i213wz/Dr.kahl%2527s_Robot.zip/file)](url)
2. Run Ikemen GO in any mode.
3. Place Dr.Kahl's Robot in position P1 or P2.
4. Press ctrl + d to check the status of the helper state.
5. Bugs are confirmed in helpers 24 and 30, which are local helpers.
6. In 1P VS 2P battle mode or watch mode (ctrl 1 and ctrl 2 required)
Use 1P or 2P as Dr. Carl's robot and hit his parts until he is destroyed.
(To check for bugs where the sound of destruction of parts is repeated continuously)

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/112223516/934d003f-a0cb-4978-bcce-884653cc7db5

### Engine Version (or source code date)

All versions of IKEMEN GO including v0.99.0-rc.4

### Operating system

Windows

**Comment by potsmugen** [comment] 2023-10-13 15:36
There's definitely something wrong with the way Ikemen handles it, but this char doesn't feel stable enough to use as a test case. It creates dozens of debug messages per frame.

But it has so many redirection errors that it might be an issue like #1388. Probably either that or some player type helper properties that work different in Ikemen.

The turning bug in that video also happens in Mugen.

**Comment by K4thos** [comment] 2024-09-03 22:47
Closing as a duplicate of 1388 for maintenance.

**Closed by K4thos** 2024-09-03 22:47 UTC
Labels: bug, duplicate
