### ISSUE TITLE
DirectX support or OpenGL for low resources

### ISSUE THREAD

**Issue by CableDorado2** [ikemen-engine/Ikemen-GO#304] opened 2021-07-20 00:29 UTC
If it is not possible to add DirectX support then is there any way to open ikemen go using opengl32.dll? Because to date when I try it loads the window, but it closes before showing the menu.

**Comment by EVILEDLIBRE** [comment] 2021-07-22 19:59
Does it give an error message? If so, what does it say?

**Comment by CableDorado2** [comment] 2021-07-22 21:06
> Does it give an error message? If so, what does it say?

It doesn't show me any error message, it just closes, but generate a .log file: https://youtu.be/jJQfilL0brw

Log file:
[Ikemen.log](https://github.com/Windblade-GR01/Ikemen-GO/files/6865217/Ikemen.log)

**Comment by EVILEDLIBRE** [comment] 2021-07-23 08:15
It's this error. It is known about.

https://github.com/Windblade-GR01/Ikemen-GO/issues/153

I can tell by your video because it says that it failed to compile version 150 core and GLSL error.

This is a known error. If I may take a guess, is you're computer is running Intel graphics?

**Comment by CableDorado2** [comment] 2021-07-23 14:08
I don't use a graphic card, but my computer should run "Intel Graphics" using a Opengl32.dll the same that I use to open the old ikemen engine without graphic card.

**Comment by EVILEDLIBRE** [comment] 2021-07-23 18:35
I never mentioned a card. Most current Intel Graphics are integrated. Though, there is the DG2 on the horizon that plans to be a discrete Intel Graphic Card.

So, read bug #153  that I linked you to. It will explain everything.

We're not exactly sure what the problem is. It's one of two things.

Scenario 1: The drivers for older / lower end Intel Graphics Chips lie to the operating systems and tells the OS that it is only compatible with the OpenGL 3.0 profile and so it sets itself to that and Ikemen Go refuses to run because it needs a higher version; even though the chip and driver are actually completely compatible.

Scenario 2: Ikemen Go is a "context unaware application" and fails to effectively probe the OS to find out which OpenGL profile it should be running the program under. At which point it defaults to the lowest thing it knows (OpenGL 3.0) for "maximum compatibility" thus breaking the program because Ikemen Go can not run under OpenGL 3.0.

I've been in talks with one of the programmers for literally over a year now. He doesn't really know how to fix it or what is causing it; and just keeps saying 'he'll look into it' but nothing ever gets fixed. He just keeps deferring it to the driver; which very well could be the problem. But, that doesn't explain why it only started to effect the program around the time the Pause Menu was added, which was a little after May 18Th, 2020. Before that time, Ikemen Go never had this error. I don't think he considers it a very high priority, as it only effects Intel Graphics. He fails to realize that a lot of people are trying to migrate from mugen and are thus trying to run Ikemen Go on very low end Intel Graphics computers. So, what should be considered a critical bug that is impeding wider program usage is swept under the rug as something that isn't considered a big deal and that doesn't effect enough people to warrant the tune for figuring out a fix for.

That might sound harsh, but it has been literally over a year and all we ever get as a response is 'will look into it, probably your driver, requirements never changed.' It's clearly being written off and not seen as a critical issue worth fixing. So, don't hold your breathe for a solution. I didn't, and eventually did my own research and found a work around that fixes the problem for me. So, it's not even really my problem anymore. That said, I feel bad for the rest of you all that are stuck with living with this error and unable to even run Ikemen Go.

In fairness, I am not even sure it is something the programmer can fix. If it's Scenario 1, then there is nothing the programmer can do. That's on whoever wrote the crappy Intel driver and nobody ever getting around to fixing it. If it's Scenario 2, then it's the fault of the people programming Ikemen Go for breaking it and refusing to take the time to fix it. If I were to take a guess, I think it's Scenario 2 because the program used to work fine back on the version from May 18Th, 2020. I think when the Pause Menu was added that it (or something else changed during that time frame) handles fonts and the GLSL font shaders in a way that breaks which OpenGL profile is chosen. I mean, what else could it really be? Ikemen Go worked on that date, and before. Pause Menu added; has had this error ever sense. Deductive reasoning would then point to looking into the changes between when the program worked and when it broke to find the error; and I have provided the timeline that this took place in. When I point this out, all I get is 'will look into it, probably your driver, requirements never changed' as if the problem is on my end when it is clearly on Ikemen Go's end. So, instead of solutions I get deflection.

Again, this isn't even my problem anymore. But, there is a long laundry list of people who can't run the program because of this and nothing ever gets done to fix it.

The solution is you need to find a way on windows to manually override the OpenGL profile when launching the program. "MESA_GL_VERSION_OVERRIDE=4.3 ./Ikemen_GO_linux" is what works for me in Konsole. I added I added the line "export MESA_GL_VERSION_OVERRIDE=4.3" to the bottom of my /etc/profile config file to force the change across my entire OS so I didn't have to launch Ikemen Go from the Konsole every time.

Windows has a pretty crappy command line program, because microsoft integrated most of windows into the GUI; rending their command line program basically useless. So, I have no idea how you could force it to run via command line. I also don't know where you can go on windows to force a system wide change to the OpenGL profile. So, your guess is as good as mine and good luck.

**Comment by K4thos** [comment] 2023-01-17 12:50
closing this one for maintained reasons since the request is also covered by more broad #404 ticket.

**Closed by K4thos** 2023-01-17 12:50 UTC
Labels: duplicate, enhancement
