### ISSUE TITLE
Palette selection is broken when several DEF files use the same SFF

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#822] opened 2023-01-21 10:22 UTC
**Describe the bug**
Title sums it up. Some characters will have more than one DEF file because of extra modes. They will usually share the SFF file. If you select the same character via different DEF files, the first player will use the palettes from the second one.

**To Reproduce**
1. [Download my Ryu](https://www.mediafire.com/file/kgmvuigv69pfib1/ryu_pots.zip/file)
2. Select a team of "normalryu.def" against a team of "evilryu.def"
3. All players will use the palettes from "evilryu.def"

**Expected behavior**
Each player should use the palettes from their own DEF file.

**Screenshots / Video**
![ikemen016](https://user-images.githubusercontent.com/107247004/213862629-182ea88d-7ece-413d-b768-7937d23e65a2.png)

**Platform (please complete the following information):**
 - Latest build
 - Windows 7

**Additional context**
This started happening in December. There's been some progress but it's still not entirely right.
This example is using SFF v1. I'm not sure if the same happens with v2.

**Comment by K4thos** [comment] 2023-01-21 22:26
regression caused by #770
@samhocevar 
in this case getOwnPalSprite called by lifebar.go fails
solution here would be checking if `def` entry in CharGlobalInfo is different, not just sff filename.

**Comment by samhocevar** [comment] 2023-01-22 07:58
This happens because parts of the `Sff` structure get modified at runtime. I don’t know if it is things `sprites` or `palList` or both, but the ideal solution would be to duplicate the modified structures at the beginning of `loadSff()` in the cache hit branch. If we don’t find the actual culprits, I will have to fully rework the cache code and ensure only textures are reused and not the whole `Sff` structure.

**Comment by K4thos** [comment] 2023-03-21 04:10
The commit that introduced this change has been reverted, so I'm closing this ticket for now.

**Closed by K4thos** 2023-03-21 04:10 UTC
Labels: bug, regression
