### ISSUE TITLE
BUG: ikaruga chars in tag mode have a funny bug

### ISSUE THREAD

**Issue by mrkarate505** [ikemen-engine/Ikemen-GO#545] opened 2022-05-30 19:12 UTC
when i select any ikaruga kof char in tag mode they are dead and jumping out of the screen like frogs LMAO
![ikemen000](https://user-images.githubusercontent.com/106555202/171049217-19f6e23c-439c-44a7-96a4-e1cd06758b32.png)
![ikemen001](https://user-images.githubusercontent.com/106555202/171049221-974b1e88-874c-4481-96d3-5158bc613208.png)

**Comment by K4thos** [comment] 2022-05-31 11:02
not a bug, Character has a conflict with state numbers used by ikemen go default tag system. As per wiki ikemen go reserves following states:
`StateTagEnteringScreen = 5600
StateTagLeavingScreen = 5610
StateTagWaitingOutside = 5611
StateTagJumpingIn = 5620
StateTagLanding = 5621`

**Comment by mrkarate505** [comment] 2022-06-01 00:19
I tried to solve it but couldn't solve it. the character transition during tag mode worked but more bugs appeared in the chars, for example all kyo made by ikaruga have moves that make p2 fly through the wall, "ex k' xi" makes p2 run behind the wall during a special move

**Comment by Kuroteba** [comment] 2022-06-02 06:04
Did you change the P2StateNo or TargetState value of the technique that causes the bug?

**Comment by mrkarate505** [comment] 2022-06-02 19:31
not yet, i just deleted the states "5600, 5610, 5611, 5620,5621" but i will test the ones you said now

**Comment by NeatUnsou** [comment] 2022-06-27 13:21
After all, each state number is just a conflict, so rewriting the following file state numbers will work perfectly for almost all characters.

common.const
```
; tag.zss states
StateTagEnteringScreen = 5600
StateTagLeavingScreen = 5610
StateTagWaitingOutside = 5611
StateTagJumpingIn = 5620
StateTagLanding = 5621
```
tag.zss
```
[StateDef 5600;

[StateDef 5610;

[StateDef 5611;

[StateDef 5620;

[StateDef 5621;
```

For example

common.const
```
; tag.zss states
StateTagEnteringScreen = 985600
StateTagLeavingScreen = 985610
StateTagWaitingOutside = 985611
StateTagJumpingIn = 985620
StateTagLanding = 985621
```
tag.zss
```
[StateDef 985600;

[StateDef 985610;

[StateDef 985611;

[StateDef 985620;

[StateDef 985621;
```

The number 5600 in the tag system has no special meaning, so the user may rewrite this number.
It would be better to change this default numbers.

**Comment by K4thos** [comment] 2022-06-30 10:25
Above commit added const support for cns/zss StateDef numbers and modified ZSS files to take advantage of it, so in next build it will be possible to solve this compatibility problem just by pasting state numbers of your choice to character's [Constants] group (or modifing common.const to implement the change globally for all characters)

**Comment by NeatUnsou** [comment] 2023-01-12 03:00
Added const support, users can now easily change the tag state number.
Therefore, we feel that there is no longer a need to keep the default tag state number as it currently is.
The number conflict problem can be solved by changing the state number in common.const,
but forcing all users playing tag to make this change is not a good workaround.
Can't close this issue on ikaruga chars without changing the common.const state number on github to another number that is less likely to conflict.

**Comment by potsmugen** [comment] 2023-01-17 08:45
I understand the sentiment behind wanting to keep all system states between 5000 and 5999 though. And Elecbyte did ask people to not use those numbers for anything.

**Closed** 2023-03-10 03:31 UTC
Labels: compatibility
