### ISSUE TITLE
Fight Screen Zoomed In

### ISSUE THREAD

**Issue by Kazama325** [ikemen-engine/Ikemen-GO#820] opened 2023-01-19 07:26 UTC
I recently discovered Ikemen and I was able to get it working but I'm having 1 issue. My screenpack is 16:9 but when I run it in Fullscreen my stages and characters seem very zoomed in. Is there a setting to fix this? The menu on the screenpack and the select screen look fine in 16:9 but when the fight starts everything is more close up than normal. When I change the aspect to 4:3 the menu is off screen and the screen isn't where it should be but the fight is not zoomed in.

The 16:9 makes it very close up
It should be zoomed out more like the image below

![mugen058](https://user-images.githubusercontent.com/123058192/213379454-9a9a5cac-6620-45e8-9632-1e55fb9bc18e.png)

Instead it looks like this, very close up. And changing my aspect ratio to 4:3 just makes my screenpack and select screen go off screen.

<img width="633" alt="Capture" src="https://user-images.githubusercontent.com/123058192/213380648-f193d396-9307-4d08-a7c6-4b57687b7c3d.PNG">

**Comment by Kazama325** [comment] 2023-01-19 07:32
This is a windowed screenshot which you may not be able to tell is very close up but if it was in fullscreen the character's heads aren't too far away from touching the life bar lol I asked other ikemen go users and they said it has been like that and there is no current fix for it so they just play in windowed mode or play with the zoom in displayed in the picture above

**Comment by K4thos** [comment] 2023-01-19 10:00
you can find details in #170, closing this one for maintenance reasons since it's a duplicate report.

**Comment by K4thos** [comment] 2023-01-19 10:09
reopening since I'm not sure if this is the same problem after reading your description again. Please upload your screenpack and both stages that you've made screenshots of in your opening post. Need to test it locally.

**Comment by Kazama325** [comment] 2023-01-19 17:32
I am trying to use this screenpack which has to be ran in 16:9

https://www.andersonkenya1.net/files/file/21626-infinite-legacy-hd-screenpack-ikemen/?_fromLogin=1

The 1st screenshot I posted isn't my mugen that's just how mugen 1.1 stages usually look. The 2nd one is my current ikemen go setup. If you use that screenpack and put the resolution to 1280*720 in fullscreen you'll see the menus and select screen look normal but the fights are much closer. It seems ALL of my stages do this and I'm not sure if its the 16:9 messing that up or the screenpack. Here is a stage to test it with. Put Ikemen in fullscreen with the screenpack at 16:9 and it'll be zoomed in. Almost like the characters are too big for the stage but I'm sure its the resolution. Custom res doesn't seem to fix it either.

I was told also that you may have to adjust ALL of your stages to make a correction possibly. I was in an Ikemen discord and someone sent me this topic and said it might work. But you'd have to tweak ALL of your stages.


https://mugenguild.com/forum/topics/project-remake-real-general-use-widescreen-169-mugen-stages-ez-way-found-187520.0.html


[War_Stage_Battle_Start.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10459337/War_Stage_Battle_Start.zip)

**Comment by Kazama325** [comment] 2023-01-19 17:36
Also not sure if this is an issue with only 1.1 stages so I included a stage that has a 1.1 and non 1.1 version.

**Comment by K4thos** [comment] 2023-01-19 20:23
as suspected it works as expected, so there is nothing new in this topic. You get the exact same result in mugen 1.0, where there is no way to letterbox mismatched localcoord stages with black bars (letterboxing). And you have the same effect in mugen 1.1 if you disable stagefit option.

Hence the problem is lack of mugen 1.1 stagefit feature, which is known (has it's own ticket dedicated to it).

**Closed by K4thos** 2023-01-19 20:23 UTC
Labels: duplicate, info needed

**Comment by Kazama325** [comment] 2023-01-19 21:16
So is there a way for me to set my stages to appear normally? Or do I just need to use non Mugen 1.1 stages? Or play in windowed lmao I'm so confused

**Comment by K4thos** [comment] 2023-01-19 21:33
Download stages that are meant for the aspect ratio you're using (16:9). Or edit stages as explained in your linked article.
