### ISSUE TITLE
Crash in fight intro, 4 round

### ISSUE THREAD

**Issue by ZyonZZ** [ikemen-engine/Ikemen-GO#1381] opened 2023-08-25 21:08 UTC
### Describe the bug

it crashed when it was in character intro
it was a 3vs3... it was the 4th round

### To Reproduce

it crashed when it was in character intro
it was a 3vs3... it was the 4th round

### Expected behavior

It was quite unexpected because I hadn't had any problems with crash until now..
chars with many megabytes? I really have no idea

### Screenshots / Video

![Nueva imagen de mapa de bitsj](https://github.com/ikemen-engine/Ikemen-GO/assets/129194444/d84a9df2-0c36-4515-8b39-2e8c4ccdea9c)

### Engine Version (or source code date)

v0.99.0-rc.2

### Operating system

Windows

**Comment by K4thos** [comment] 2024-09-03 21:23
closing since there is not enough info to reproduce it

**Closed by K4thos** 2024-09-03 21:23 UTC
Labels: not reproducible
