### ISSUE TITLE
DCL Hulk throw bug

### ISSUE THREAD

**Issue by jenngra505** [ikemen-engine/Ikemen-GO#595] opened 2022-07-01 02:19 UTC
Hulk's backthrow send the opponent flying towards the back corner at the end, if used in IKEMEN it will launch the opponent towards the front corner.

**To Reproduce**
1. Download DCL's Hulk https://drive.google.com/file/d/1RQLHgKqQKJxWEDmR6qZ5Zwb8YnDdMmT0/view
2. Start the match and perform his backthrow by holding back and pressing y in the back corner
3. See the error

**Expected behavior**
The wall bounce goes towards the back corner.

**Screenshots / Video**
[If applicable, add screenshots and/or videos to help explain your problem.](https://user-images.githubusercontent.com/18198665/176810279-f8c4a2d9-161a-41d0-8eb2-a2ff5a708cbe.mp4
)

**Platform**
 - 0.98.2
 - Windows 10

**Comment by EgyLynx** [comment] 2022-07-01 18:36
In tat logiic JKFM get throw at back... but no...

??

**Comment by K4thos** [comment] 2023-01-08 22:38
can't reproduce on 0.98.2. Tried many times. More detailed repro steps are needed, ideally with exact x postion that the character has to be to reproduce the problem.

https://user-images.githubusercontent.com/8928195/211222623-2dcaa7e1-ec39-491f-a4e9-252c5596e57d.mp4

**Comment by jenngra505** [comment] 2023-01-22 14:43
The character might have been updated with changes to the code that makes it more compatible with IKEMEN. I'll have to compare the version I have with the latest update.

**Comment by K4thos** [comment] 2023-01-22 15:15
confirmed that it's already fixed by one of the recent commits

**Closed by K4thos** 2023-01-22 15:15 UTC
Labels: bug, duplicate
