### ISSUE TITLE
Anim of character shaking

### ISSUE THREAD

**Issue by leandrooffline** [ikemen-engine/Ikemen-GO#279] opened 2021-06-18 00:00 UTC
Anim of character shaking in ikemen 0.97

https://user-images.githubusercontent.com/4389151/122485940-7474c180-cfae-11eb-898b-c0cc01147b57.mp4

**Comment by K4thos** [comment] 2021-06-23 14:04
Please test if it still happens with attached executable:
[Ikemen_GO.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6702276/Ikemen_GO.zip)
It's most likely regression caused by this commit: https://github.com/K4thos/Ikemen_GO/commit/f1928b27ecb3173cb9b7eb01c3e93c66815534d0
Partially already reversed (but this commit is newer than 0.97.0) https://github.com/K4thos/Ikemen_GO/commit/69bf6d4d82a37e6d8bca8f3b1b1ec43eaa72d1d6

**Comment by leandrooffline** [comment] 2021-06-24 13:56
I tested the exe and now not shaking any more.

https://user-images.githubusercontent.com/4389151/123274738-2a25a000-d4da-11eb-8c04-9732ca8c826e.mp4

**Comment by K4thos** [comment] 2021-06-24 21:46
> Obs.: The Exploid's sizes and positions are wrong in this exe test.
I will need your game to test it. Please delete chars, music, stages and upload the rest.

**Comment by leandrooffline** [comment] 2021-06-25 23:14
>I will need your game to test it if this is intended behaviour. Please delete chars, music, stages and upload the rest.

I do a lite version with 0.97 base
the exploid can change in common1.cns Statedef 400004
use **Ikemen_GO_test.exe** for test.

https://www.mediafire.com/file/xf46haae5c46dv3/ikemen.zip/file

**Comment by K4thos** [comment] 2021-06-26 13:11
thanks, I've reverted commit that introduced support for lifebar [FightFx] scale responsible for this. It's related to this ticket: https://github.com/Windblade-GR01/Ikemen-GO/issues/20

**Comment by K4thos** [comment] 2021-07-08 00:29
second problem has been now fixed without disabling [FightFx] scale. Now the result is exactly the same as in mugen (not necessarily one you're expecting though)
Mugen 1.1:

![mugen000](https://user-images.githubusercontent.com/8928195/124844124-c5674c80-df93-11eb-915c-78f64ec8b605.png)

Ikemen:

![ikemen000](https://user-images.githubusercontent.com/8928195/124844131-cb5d2d80-df93-11eb-8cc7-79c7188f955e.png)

The reason for different placment and scale than expected is your incorrect usage of Const480p and Const240p in Statedef 400004 Explod pos and scale parameters. The fact that you had to use them in the first place was ikemen go bug since that's not how mugen works.

**Closed** 2022-03-23 19:23 UTC
Labels: bug
