### ISSUE TITLE
If Postype produces a Left or Right projectile when facing right, the display position will be incorrect.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#1857] opened 2024-06-27 05:58 UTC
### Describe the bug

The position of some explods and projectiles to be displayed is different from MUGEN.

Example: Fire-Shuzo's ひよこ (Lv.1, only when it is displayed facing left), しじみ　強 (Lv.2)
Breakthrough of The Animated Colonel

### To Reproduce

1.Fire-Shuzo's ひよこ out facing left. (Command is 64 + A or B, Statedef is 1600)
  Or, at lv.2, しじみ　強. (Command is 236 + Y, Statedef is 1010. To get to Lv.2, use the move that comes out with 22 + C once or 
  choose from 7P to 11P colors)
  Or hit Breakthrough by The Animated Colonel.

### Expected behavior

The position of some explods and projectiles to be displayed is different from MUGEN.

### Engine Version (or source code date)

v0.99.0 and nightly

### Operating system

Windows

### Extra context or search terms

Fire-Shuzo's DL link.

https://ux.getuploader.com/SY77P/download/87

**Comment by Kuroteba** [comment] 2024-07-08 06:02
Fire-Shuzo's ひよこ problem was resolved in the 07/03 NIGHTLY.
I now have more details on the other two issues, but I will close this because I want to present them separately.

**Comment by Kuroteba** [comment] 2024-07-10 06:17
Sorry, the bug I mentioned before about the display position being incorrect when Postype produces a Left or Right projectile when facing right was not fixed.
I will put up a video below.


https://github.com/ikemen-engine/Ikemen-GO/assets/99640380/a3522562-8dd2-4e4b-b802-dcf39a1b138d

**Comment by K4thos** [comment] 2024-09-03 21:14
closing as duplicate of #1881 (keeping that one due to the additional info)

**Closed as completed by K4thos** 2024-09-03 21:14 UTC
Labels: bug, duplicate
