### ISSUE TITLE
The quasi-state fix does not work with the player helper at 5150 states, and the EnemyNear redirect (and possibly the Enemy redirect as well) is working on the player helper as well.

### ISSUE THREAD

**Issue by kousamugen** [ikemen-engine/Ikemen-GO#592] opened 2022-06-30 09:45 UTC
The quasi-state fixation does not work when the player helper is in the 5150 state, for example, the player character turns in the direction of the player helper even if the player helper is in the 5150 state.
Also, EnemyNear is applied to the player helper, which causes problems with characters using EnemyNear, etc.
I would like to see the above specifications changed to the same specifications as winmugen or MUGEN 1.0+.

Engine Version:All Version 
OS:Windows 10

**Comment by K4thos** [comment] 2022-06-30 13:06
can't reproduce. Player character doesn't turn in the direction of the player helper when the player helper is in the 5150 state:

https://user-images.githubusercontent.com/8928195/176683010-36d57647-c473-48d2-b7e2-7027640eb61c.mp4

EnemyNear is not applied to the player helper:

![ikemen003](https://user-images.githubusercontent.com/8928195/176684239-a9586eb9-1349-46b8-97f3-42f632a93b8e.png)

Please prepare simple test case using kfm that showcases differences between mugen and ikemen. And reproduction steps, not just written description.

**Comment by kousamugen** [comment] 2022-06-30 13:37
I'm sorry.
By quasi-state fixed, I mean that the state processing is done in such a way that the final processing of the state ends at 5150.
It's like putting 5150 selfstate at the end of each state.
In winmugen, there is a spec that characters loaded at 5150 are not redirected from other players by P2 Redirect
This only works if helpertype=player, so do not do it with helpertype=normal.
Thanks again for the advice, I will take care in the future.

**Comment by kousamugen** [comment] 2022-06-30 14:01
Also, the EnemyNear question goes like this
IKEMEN GO ver is 0.98.2
Is this a 0.98.2 only problem? (I refer to EnemyNear in var(7).)
![ikemen000](https://user-images.githubusercontent.com/108460494/176697082-04fd365c-6e13-4175-9d1a-b43057ea05fb.png)

**Comment by kousamugen** [comment] 2022-06-30 14:07
I verified again that there was no enemy sensing to the 5150 state player helper.
Does this mean that it is stealthy?
If so, I apologize again for the lack of confirmation.
I am also very sorry for the repeated posts.
![ikemen002](https://user-images.githubusercontent.com/108460494/176698242-8c8142a8-91ff-4da8-b57b-432a5cc774e6.png)

**Comment by kousamugen** [comment] 2022-06-30 14:08
Thanks for the validation on EnemyNear!

**Comment by K4thos** [comment] 2023-02-13 02:25
Closing it since I don't think there is anything to fix here (provide more details please if that's not the case). If you mean that EnemyNear can't detect helper type=player in death state than it's intentional. You can reenable it on per character basis via [Constants] Default.IgnoreDefeatedEnemies = 0 (details on wiki) or globally via data/constants.const

**Closed by K4thos** 2023-02-13 02:25 UTC
Labels: info needed
