### ISSUE TITLE
Dee bee kaw's strong attack is not working and not implemented

### ISSUE THREAD

**Issue by cyliamargatroid** [ikemen-engine/Ikemen-GO#363] opened 2021-10-05 07:22 UTC
In IKEMEN GO, Dee Bee Kaw's Strong attack can't seem to send a Target crashing to the wall.
In MUGEN, Dee Bee Kaw's Strong attack does send a Target crashing to the wall.

Starting at line 24779 in ```stateoftheart.cns```, Ikemen go can't seem to read this line really well.

Tested Character: Dee Bee Kaw by The_None (Using MUGEN 1.0 version)

Link: http://www.justnopoint.com/lbends/index.php?location=chars&page=2

**Comment by cyliamargatroid** [comment] 2021-10-05 09:01
Bug review - https://streamable.com/8pk49i

**Comment by K4thos** [comment] 2021-10-05 10:40
please always provide repro steps (in this case command that should be performed). I don't know how to do that punch attack. Kick seems to be working just fine:
https://user-images.githubusercontent.com/8928195/136006824-95c6c5a6-e2cf-4a1c-98a2-1e79508e0eae.mp4

> Starting at line 24779 in stateoftheart.cns, Ikemen go can't seem to read this line really well.
bug in character cns (the reason why mugen doesn't complain about it is because ForceFeedback sctrl is completely ignored by it since dosmugen). You need to change `waveform = "sine"` to `waveform = sine`, as per documentation.

This state controller is not usable yet since we're waiting for glfw guys to finish rumble support, but 0.98 compiler already can read it. We could comment it out for now but I don't see much point since exact same error will show up once full ForceFeedback sctrl support is implemented anyway.

**Comment by K4thos** [comment] 2021-10-05 10:54
> In IKEMEN GO, Dee Bee Kaw's Strong attack can't seem to send a Target crashing to the wall.

It's known. The reason for this is this feature (support for loading negative state from multiple files): https://github.com/K4thos/Ikemen_GO/wiki/Miscellaneous-Info#states
what happens is that the 1.0 version of the character uses different DEF file that loads additional 10ov.st file before stateoftheart.cns. This st file contains completly duplicated [Statedef -2], meant to override the same code from stateoftheart.cns
We're planning to change how negative states appending works in future for better compatibility with mugen content. Although The_None is the only creator that I'm aware of, who uses negative state overriding like this, so this is not an urgent matter

> Starting at line 24779 in stateoftheart.cns, Ikemen go can't seem to read this line really well.

it's a bug in character cns (the reason why mugen doesn't complain about it is because ForceFeedback sctrl is completely ignored by it since dosmugen). You need to change `waveform = "sine"` to `waveform = sine`, as per documentation.

This state controller is not usable yet since we're waiting for glfw guys to finish rumble support, but 0.98 compiler already can read it. We could comment it out for now but I don't see much point since exact same error will show up once full ForceFeedback sctrl support is implemented anyway.

**Comment by VinVulpis** [comment] 2021-12-14 22:39
I fixed Dee Bee Kaw (and Segalow) both with there wall bounces not working by:

For Dee Bee Kaw it's State 210 "strong punch", and 1280 "EX kenshiro from KoF"
For Segalo they are 1050, 1060, and 1070, all of his "SUCKer Punch" moves.

Look for the `TargetState` STCTRL and change `trigger1 = Var(21)=1` to `trigger1= movehit=1`. I looked in the code and `var(21)` is only being used as another way to track `movehit`, and for some reason on those moves, it only don't work on some fo the custom states, it's weird, but this fixed it for them both.

**Comment by K4thos** [comment] 2021-12-15 00:20
VinVulpis, I don't think you understand what overriding states means. What you did is a workaround, not a fix (complete duplicate of Statedef -2 is still appended and can cause issues). All you had to do to solve it is removing all statedef -2 states that are duplicated.

**Comment by VinVulpis** [comment] 2021-12-15 00:49
Oohh, RIght, those files have two sets of -2 and Ikemen adds them, not replace. Riiiight. I'm a doof. Hahah.

**Closed** 2022-06-14 14:20 UTC
Labels: compatibility

**Comment by D4sty** [comment] 2022-11-25 19:41
> I fixed Dee Bee Kaw (and Segalow) both with there wall bounces not working by:
> 
> For Dee Bee Kaw it's State 210 "strong punch", and 1280 "EX kenshiro from KoF" For Segalo they are 1050, 1060, and 1070, all of his "SUCKer Punch" moves.
> 
> Look for the `TargetState` STCTRL and change `trigger1 = Var(21)=1` to `trigger1= movehit=1`. I looked in the code and `var(21)` is only being used as another way to track `movehit`, and for some reason on those moves, it only don't work on some fo the custom states, it's weird, but this fixed it for them both.



Mind telling me how to fix them? I tried adding these two on ikemen but they crashed
