### ISSUE TITLE
v0.98.2 is handling palettes in reverse for Arcade CPU

### ISSUE THREAD

**Issue by V-Holder** [ikemen-engine/Ikemen-GO#715] opened 2022-11-13 16:50 UTC
**Describe the bug**
Compared to any other version of MUGEN or IKEMEN, the newest version seems to invert the intended palette order for most characters. Characters that should pick pal1 in Arcade Mode as CPU opponents pick pal4 instead.

**To Reproduce**
Detailed steps to reproduce the behavior, e.g.:
1. Download character from https://www.mediafire.com/file/kgmvuigv69pfib1/ryu_pots.zip/file (just an example of character who should pick pal1 as a CPU opponent)
2. Start a match in Arcade or Boss Rush mode with Random Color disabled and go up against Ryu while using any other character
3. Ryu will wear a secondary palette (light blue gi with white band) instead of pal1 (classic worn white gi with red band)

**Expected behavior**
Characters following the correct palette order from their .def files, prioritizing pal1 instead of pal4.

**Platform (please complete the following information):**
 - Engine Version: v0.98.2
 - OS: Windows 11

Addendum: This issue can also be observed in the Street Fighter All-Stars fullgame: https://drive.google.com/file/d/16jAiyUZrTgTKfsqT9ORtFwIuJTuji8Gd/view

**Comment by K4thos** [comment] 2022-11-19 11:47
it's already fixed on github build

**Closed by K4thos** 2022-11-19 11:47 UTC
Labels: bug

**Comment by V-Holder** [comment] 2022-11-20 21:09
Just tested it on the current build and the same issue persists. Here's Ryu wearing pal4 when he should be wearing pal1.
![untitled](https://user-images.githubusercontent.com/102410797/202926334-75796ecd-13bf-4734-9a28-1cc888809b52.PNG)

**Comment by K4thos** [comment] 2022-11-20 21:13
I can't reproduce it with the exact same Ryu with build compiled out of source code, while being able to do it on 0.98.
