### ISSUE TITLE
Bugs #2207 and #2214 have not been fixed.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#2219] opened 2024-12-30 04:24 UTC
### Describe the bug

Bugs #2207 and #2214 have not been fixed.

### To Reproduce

1.Download the nightly build version of the 12/30/2024 edition.
2.The behavior confirms the bugs in #2207 and #2214.
3.The above bug may occur and the bug has not been fixed.

### Engine Version (or source code date)

12/30/2024 - nightly

### Operating system

Windows

**Comment by K4thos** [comment] 2024-12-30 07:05
can't reproduce. More accurate repro steps are needed.

**Comment by Kuroteba** [comment] 2024-12-30 07:26
A bug was identified in which the cross buttons on the GamePad F310 sometimes did not work on the title screen.
We have identified a bug that may prevent the user from using the Up, Left, Right, and Down keyboard controls and controller controls on the character select screen and in training mode.
(The nightly build version of the 12/02/2024 edition did not have this bug.)

**Comment by K4thos** [comment] 2024-12-30 07:32
edit: I was able to reproduce #2214 on match started via command line. Will be fixed.

**Closed as completed** 2024-12-30 08:01 UTC
Labels: bug, regression, group: input
