### ISSUE TITLE
General Bugs

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#520] opened 2022-05-12 22:36 UTC
**1 - It is not possible to use any other font in the menu footer than the default one.**
**2 - Options margin.y**

**2.a.** The options cursor's y coordinates impact the height of the boxbg.
Default code: menu.boxcursor.coords = -5, -10, 154, 3
![ikemen000](https://user-images.githubusercontent.com/68881657/168174825-b4590d2a-ac8d-4aa3-9a09-2def801f8612.png)

Now if I decrease one pixel from the y2 coordinate:
menu.boxcursor.coords = -5, -10, 154, 2
This happens:
![ikemen001](https://user-images.githubusercontent.com/68881657/168175273-fe1f2972-1e65-4f20-a64b-2c331896bf7a.png)

**2.b.** It is also not possible to change the height of the boxbg using the parameter set for it.
Default: menu.window.margins.y = 0,0 (check the 1st image)

Alteration: menu.window.margins.y =-20,20 
![ikemen002](https://user-images.githubusercontent.com/68881657/168176198-aced1744-16c3-423b-82f3-9d4329fb3a75.png)

Not only is there no change in height, these -20 pixels from the first value are cut off from the text. The second value just doesn't work.

**3 - SHIFT+F4 don't reset the music.**
**4 - Win Matches and Score reset if the Player is challenged.**
**5 - [Training Info] values are still shared with [Menu Info] even if you use custom ones.**

 For example:
[Menu Info]
...
menu.window.visibleitems = 13
menu.boxcursor.visible = 1
menu.boxcursor.coords = -5, -10, 154, 3

[Training Info]
...
menu.window.visibleitems = 5
menu.boxcursor.visible = 1
menu.boxcursor.coords = -5, -10, 154, 13

There are no changes in the training menu.

**6 - "p2.cursor.blink = 1" doesn't work** 
When the cursors of P1 and P2 are in the same slot, this parameter does not work. I didn't get to test it, but I suppose it must be the same with the P3 and P4.

**7 - sounds.enabled = 0 doesn't work**
On result screens the character sounds still play. Tested on the Continue, Victory and Survival screens.

**8 - Position of characters in result screens**
In the result screens, chars appear where they were at the end of the fight, is that intentional?
In MUGEN, only P1 appears, so they always appear in the center of the screen, but since in IKEMEN we can have both players (and/or teams), the best approach, in my opinion, would be for them to appear in their respective starting positions (in the positions defined in the stage def  - pxstartx).

**9 - Bugged screenshots**
Here's a bug that happens every now and then: 
![buggedscreen](https://user-images.githubusercontent.com/68881657/169156011-d110e757-a3fc-4a41-9482-b4a8d090ad08.png)

Normal screen
![nobuggedscreen](https://user-images.githubusercontent.com/68881657/169156057-3ed0a70f-04a4-4432-9ed0-e63d084ccad5.png)

Happened with different screenpacks.
When I press F12 the screen flashes without the elements and next time it works normally. It's not a terrible thing, but I think it's worth reporting.

**10 - Rendering issues with center-aligned fonts**
A bug that was introduced in version 0.98.2. Sometimes the fonts will appear broken. In the titles of some modes, the fonts will be fine, but in others they will appear poorly rendered:

![fontcomparison](https://user-images.githubusercontent.com/68881657/170505012-bd8a58d6-977b-4524-bb90-76263c7de38a.png)
Tested with v1 and v2 (indexed) fonts. In smaller fonts they are more noticeable, but it is a problem that can be seen in any font.
 Apparently this only happens if localcoord = 640x480. Tried it in 320x240 and 1280x720 and it's fine.

**Comment by K4thos** [comment] 2022-07-20 22:17
> 1 - It is not possible to use any other font in the menu footer than the default one.
Can't reproduce, refer to system.base.def

> 2.a. The options cursor's y coordinates impact the height of the boxbg.
Already fixed.

> 3 - SHIFT+F4 don't reset the music.
Intentional. Maybe will be changed in future during scripts refactoring.

>  4 - Win Matches and Score reset if the Player is challenged.
can't reproduce. From what I see score goes back to value from the start of match (so 0 if it's match 1), which is how it's supposed to work

>  5 - [Training Info] values are still shared with [Menu Info] even if you use custom ones.
fixed

> 6 - "p2.cursor.blink = 1" doesn't work
implemented

> 7 - sounds.enabled = 0 doesn't work
> On result screens the character sounds still play. Tested on the Continue, Victory and Survival screens.
should be already fixed. If it still happens in next build than open a new ticket but don't forget to upload character that can reproduce the problem

> 8 - Position of characters in result screens
> In the result screens, chars appear where they were at the end of the fight, is that intentional?
It is intentional and won't be changed.

> 9 - Bugged screenshots
should be fixed by upcoming scripts refactoring, most likely cased by rendering during frameskip

> 10 - Rendering issues with center-aligned fonts
consider opening a new ticket for this one. Doubt you will see any changes to how the engine handles scaling any time soon tho.

---------------

Thanks for reports. In future please create 1 ticket per bug report with appropriate ticket name, instead of making grouped topics.

**Closed by K4thos** 2022-07-20 22:17 UTC
Labels: bug
